--aula 1905
CREATE DATABASE VENDA;

USE VENDA;

--COMANDO PARA CRIAR A TABELA CLIENTE
CREATE TABLE CLIENTE (
	COD_CLIENTE INT NOT NULL PRIMARY KEY,
	NOME VARCHAR (50) NOT NULL,
	CPF VARCHAR (11) NOT NULL,
	TELEFONE BIGINT,
	ENDERECO VARCHAR (100) NOT NULL,
	CIDADE VARCHAR (100) NOT NULL
);

CREATE TABLE VENDEDOR (
	MATRICULA INT NOT NULL PRIMARY KEY IDENTITY (200, 1), --AUTOINCREMENTO DE 1 EM 1 A PARTIR DE 200
	NOME VARCHAR (50) NOT NULL,
	TELEFONE BIGINT,
	ENDERECO VARCHAR (100) NOT NULL,
	SALARIO FLOAT NOT NULL,
	CPF VARCHAR (11) NOT NULL
);

CREATE TABLE VENDA (
	COD_VENDA INT NOT NULL PRIMARY KEY IDENTITY (300, 1),
	DATA_VENDA DATE NOT NULL,
	VALOR FLOAT NOT NULL,
	COD_CLIENTE INT NOT NULL,
	MATRICULA INT NOT NULL
);

CREATE TABLE PRATELEIRA (
	COD_PRATELEIRA INT NOT NULL PRIMARY KEY,
	LOCALIZACAO VARCHAR (50) NOT NULL,
	SETOR VARCHAR (50)
);

CREATE TABLE PRODUTO (
	COD_PRODUTO INT NOT NULL PRIMARY KEY,
	NOME VARCHAR (100) NOT NULL,
	MARCA VARCHAR (50) NOT NULL,
	VALOR FLOAT NOT NULL,
	COD_PRATELEIRA INT 
	CONSTRAINT FK_PRATELEIRA FOREIGN KEY REFERENCES PRATELEIRA (COD_PRATELEIRA)
);

CREATE TABLE ITEM_VENDA (
	COD_ITEM INT NOT NULL PRIMARY KEY IDENTITY (1001, 1),
	COD_VENDA INT NOT NULL FOREIGN KEY REFERENCES VENDA (COD_VENDA),
	COD_PRODUTO INT NOT NULL FOREIGN KEY REFERENCES PRODUTO (COD_PRODUTO)
);


-- COMANDO PARA ALTERAR A TABELA VENDA E INCLUIR A CHAVE ESTRANGEIRA (CLIENTE E VENDEDOR)
ALTER TABLE VENDA
ADD CONSTRAINT FK_CLIENTE FOREIGN KEY (COD_CLIENTE) REFERENCES CLIENTE (COD_CLIENTE);

ALTER TABLE VENDA 
ADD CONSTRAINT FK_VENDEDOR FOREIGN KEY (MATRICULA) REFERENCES VENDEDOR (MATRICULA);

-- COMANDO PRA INCLUIR A CHAVE ESTRANGEIRA NA TABELA PRODUTO DE PRATELEIRA
ALTER TABLE PRODUTO
ADD CONSTRAINT FK_PRATELEIRA FOREIGN KEY (COD_PRATELEIRA) REFERENCES PRATELEIRA (COD_PRATELEIRA);

-- INCLUIR CHAVE ESTRANGEIRA DE PRODUTO E VENDA NA TABELA ITEM_VENDA
ALTER TABLE ITEM_VENDA
ADD CONSTRAINT FK_PRODUTO FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO (COD_PRODUTO);

ALTER TABLE ITEM_VENDA
ADD CONSTRAINT FK_VENDA FOREIGN KEY (COD_VENDA) REFERENCES VENDA (COD_VENDA);

alter table CLIENTE
add SOBRENOME varchar(50) not null;

select * from VENDA;

--duas insercoes em cada tabela
insert into CLIENTE
	values (5555, 
	'BRENER',
	'48097087804',
	1139740876,
	'PAULO BARRETO, 423',
	'SAO PAULO',
	'ANDRADE'
	);

insert into CLIENTE
	values (6666, 
	'ARI',
	'01137066857',
	11996216104,
	'DELFINO DE MELLO, 111',
	'SAO PAULO',
	'AMARAL'
	);

INSERT INTO VENDEDOR
	VALUES('MARTA',
	11993167521,
	'AV PAULISTA, 564',
	6152.56,
	'04634477866'
	);

INSERT INTO VENDEDOR
	VALUES('BELISA',
	1139746666,
	'PRACA GAGO COUTINHO, S/N',
	7559.74,
	'22255588866'
	);

SELECT * FROM VENDA;

INSERT INTO PRODUTO
	VALUES(7777,
	'NOTEBOOK',
	'HP',
	999.99,
	2
	);

INSERT INTO PRODUTO
	VALUES(2222,
	'DESKTOP',
	'CORPC',
	1999.99,
	1
	);

INSERT INTO PRATELEIRA
	VALUES(1, 
	'ARMAZEM',
	1
	);

INSERT INTO PRATELEIRA
	VALUES(2, 
	'LOJA',
	2
	);

INSERT INTO VENDA
	VALUES('2021-06-05',
	7999.99,
	5555,
	200
	);

INSERT INTO VENDA
	VALUES('2021-05-19',
	2999.99,
	6666,
	201
	);

INSERT INTO ITEM_VENDA
	VALUES(300,
	7777
	);

INSERT INTO ITEM_VENDA
	VALUES(301,
	2222
	);

--BUSCRA CLIENTES QUE MORAM EM SAO PAULO
SELECT NOME FROM CLIENTE
WHERE CIDADE = 'SAO PAULO';

--LISTAR O CPF DO CLIENTE BRENER
SELECT CPF FROM CLIENTE
WHERE NOME = 'BRENER';

--LISTAR A DATA DA VENDA DE CODIGO 300
SELECT DATA_VENDA FROM VENDA
WHERE COD_VENDA = 300;