--aula 02/06

USE VENDA;

SELECT * FROM PRODUTO;

--LISTAR O NOME DO PRODUTO QUE TEM MENOR VALOR 
SELECT NOME FROM PRODUTO
WHERE VALOR =(SELECT MIN(VALOR) FROM PRODUTO);

ALTER TABLE VENDEDOR
ADD SOBRENOME VARCHAR(50);

--LISTAR VENDEDOR QUE NAO FEZ VENDA 
SELECT NOME, SOBRENOME FROM VENDEDOR
WHERE MATRICULA NOT IN 
(SELECT VD.MATRICULA FROM VENDEDOR VD, VENDA V
WHERE VD.MATRICULA = V.MATRICULA);

--BUSCAR O MAIOR SALARIO
SELECT NOME, SOBRENOME, IDADE FROM VENDEDOR
WHERE SALARIO = (SELECT MAX(SALARIO) FROM VENDEDOR)
ORDER BY IDADE DESC;

--LISTAR A MEDIA DO SALARIOS DOS VENDEDORES SUPERIOR A 35 ANOS
SELECT AVG(SALARIO) FROM VENDEDOR
WHERE IDADE > 35;

--LISTAR QTD DE VENDEDOR E MEDIA SALARIAL NA DATA 19/05
SELECT COUNT(VD.MATRICULA) AS CONTADOR, AVG(VD.SALARIO)
FROM VENDEDOR VD, VENDA V
WHERE VD.MATRICULA = V.MATRICULA
AND V.DATA_VENDA = '19/05/2021';

--BUSCA DE VENDAS DO VENDEDOR BELISA
SELECT COUNT(VD.MATRICULA) AS CONTADOR FROM VENDEDOR VD, VENDA V
WHERE VD.MATRICULA = V.MATRICULA
AND VD.NOME = 'BELISA';

SELECT COUNT(NOME) AS CONTADOR FROM VENDEDOR
WHERE MATRICULA NOT IN (SELECT VD.MATRICULA FROM VENDEDOR VD, VENDA V
WHERE VD.MATRICULA = V.MATRICULA);

--CALCULAR A SOMA DOS SALARIOS DOS VENDEDORES QUE PARTICIPARAM DE PELO MENOS UMA VENDA
SELECT SUM(SALARIO) AS SOMA_VENDAS FROM VENDEDOR; 
WHERE MATRICULA IN (SELECT VD.MATRICULA FROM VENDEDOR VD, VENDA V
WHERE VD.MATRICULA = V.MATRICULA);

-- PARA CADA UMA DAS CIDADES LISTAR O NOME E QTD DE CLIENTES QUE MORAM NELA 
SELECT CIDADE, COUNT(COD_CLIENTE) FROM CLIENTE
GROUP BY CIDADE
HAVING COUNT(COD_CLIENTE) > 2;