--aula 2605

use VENDA;

select * from VENDA;
select * from VENDEDOR;

--alterar a tabela vendedor e incluir a coluna idade
alter table VENDEDOR
add IDADE int;

--ATUALIZAR O ENDERECO DO CLIENTE 5555
UPDATE CLIENTE 
SET ENDERECO = 'AV PAULISTA, 1220'
WHERE COD_CLIENTE = 5555;

--AUMENTAR O SALARIO DOS VENDEDORES 
UPDATE VENDEDOR 
SET SALARIO = SALARIO +(SALARIO * 0.1);

--BUSCA 
SELECT *, SALARRIO = SALARIO * 1.10 FROM VENDEDOR;

INSERT INTO VENDA
	VALUES('2021-05-26',
	499.98,
	6666,
	201
	);

--EMCONTRAR O CODIGO DOS CLIENTES QUE PARTICIPARAM DE ALGUMA VENDA
SELECT COD_CLIENTE FROM VENDA;
SELECT * FROM VENDA;

SELECT DISTINCT COD_CLIENTE, MATRICULA FROM VENDA;

--ENCONTRAR O CODIGO DOS CLIENTES QUE VIVEM NA CIDADE DE SAO PAULO
SELECT COD_CLIENTE FROM CLIENTE
WHERE CIDADE = 'SAO PAULO';

SELECT MATRICULA FROM VENDEDOR
WHERE SALARIO > 2000 AND IDADE IS NULL;

SELECT MATRICULA FROM VENDEDOR
WHERE SALARIO > 6000 OR IDADE IS NULL;

--BUSCA ORDENADA --LISTAR O NOME DOS VENDEDORES E SEUS SALARIOS E ORDENAR DE FORMA ASCENDENDTE
SELECT NOME, SALARIO FROM VENDEDOR
ORDER BY SALARIO ASC; --CRESCENTE
//
SELECT NOME, SALARIO FROM VENDEDOR
ORDER BY SALARIO DESC; --DECRESCENTE

SELECT NOME, SALARIO FROM VENDEDOR
ORDER BY NOME, SALARIO;

--JOIN --JUNCAO
--LISTAR O CODIGO DAS VENDAS E O NOME DO VENDEDOR 
SELECT VENDA.COD_VENDA, VENDEDOR.NOME FROM VENDA, VENDEDOR
WHERE VENDA.MATRICULA = VENDEDOR.MATRICULA;

--ALIAS (APELIDO)
SELECT V.COD_VENDA, VD.NOME AS NOME_VENDEDOR FROM VENDA V, VENDEDOR VD
WHERE V.MATRICULA = VD.MATRICULA;

--LISTAR NOME DOS VENDEDORES QUE FIZERAM ALGUMA VENDA NO DIA 19/052021
SELECT VD.NOME FROM VENDEDOR VD, VENDA V
WHERE VD.MATRICULA = V.MATRICULA
AND V.DATA_VENDA = '19/05/2021';

SELECT VD.NOME FROM VENDEDOR VD, VENDA V
WHERE VD.MATRICULA = V.MATRICULA
AND V.DATA_VENDA BETWEEN '19/05/2021' AND '26/05/2021';

--LISTAR OS NOMES DOS CLIENTES QUE RESIDEM NA MESMA CIDADE QUE BRENER
SELECT NOME FROM CLIENTE
WHERE NOME <> 'BRENER'
AND CIDADE IN (SELECT CIDADE FROM CLIENTE 
				WHERE NOME = 'BRENER');

--CALCULAR MMEDIA SALARIAL DOS VENDEDORES
SELECT AVG(SALARIO) AS MEDIA_SALARIAL FROM VENDEDOR;

--MAIOR SALARIO
SELECT MAX(SALARIO) AS MAIOR_SAÇARIO FROM VENDEDOR;

--MENOR SALARIO
SELECT MIN(SALARIO) AS MENOR_SALARIO FROM VENDEDOR;

--COUNT
SELECT COUNT(MATRICULA) FROM VENDEDOR;

SELECT COUNT(DATA_VENDA) FROM VENDA;

--PARA CADA VENDEDOR, SELECIONAR O NUMERO DA MATRICULA E A SOMA DOS PRODUTOS VENDIDOS POR ELE
SELECT VD.MATRICULA, SUM(P.VALOR) TOTAL_VENDIDO 
FROM VENDEDOR VD, PRODUTO P, VENDA V, ITEM_VENDA I
WHERE VD.MATRICULA = V.MATRICULA
AND V.COD_VENDA = I.COD_VENDA
AND P.COD_PRODUTO = I.COD_PRODUTO
GROUP BY VD.MATRICULA;
